-- Add up migration script here
CREATE TYPE org_status AS ENUM('active');

CREATE TABLE orgs (
    "id" INT GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(64) NOT NULL,
    "status" ORG_STATUS NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,

    PRIMARY KEY(id)
);

CREATE TYPE org_membership_status AS ENUM('pending', 'accepted');
CREATE TYPE org_membership_role AS ENUM('member', 'owner');

CREATE TABLE org_membership(
    "id" INT GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT NOT NULL,
    "org_id" INT NOT NULL,
    "status" ORG_MEMBERSHIP_STATUS NOT NULL,
    "role" ORG_MEMBERSHIP_ROLE NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,

    PRIMARY KEY(id),
    CONSTRAINT fk_org_membership_user
        FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_org_membership_org
        FOREIGN KEY(org_id)
        REFERENCES orgs(id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_org_membership_prevent_duplicate ON org_membership(user_id, org_id);
CREATE INDEX idx_org_membership_user_id ON org_membership(user_id);
CREATE INDEX idx_org_membership_org_id ON org_membership(org_id);
