-- Add up migration script here
CREATE TABLE users (
    "id" INT GENERATED BY DEFAULT AS IDENTITY,
    "email" VARCHAR(320) NOT NULL,
    "password" TEXT NOT NULL,
    "display_name" VARCHAR(256) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "is_onboarded" BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY(id)
);

CREATE UNIQUE INDEX idx_users_email ON users(email);
