-- Add up migration script here
CREATE TYPE org_status AS ENUM('active');

CREATE TABLE orgs (
    "id" INT GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(64) NOT NULL,
    "status" ORG_STATUS NOT NULL,

    PRIMARY KEY(id)
);

CREATE TABLE org_membership(
    "id" INT GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INT NOT NULL,
    "org_id" INT NOT NULL,

    PRIMARY KEY(id),
    CONSTRAINT fk_org_membership_user
        FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_org_membership_org
        FOREIGN KEY(org_id)
        REFERENCES orgs(id)
        ON DELETE CASCADE
);
