includeWorkspaceRoot: true

packages:
    - "apps/*"
    - "packages/*"

overrides:
    "magicast": "^0.3.5"
    "vue": "^3.5.25"

catalog:
    "@eslint/compat": "^1.4.1"
    "@eslint/js": "^9.36.0"
    "eslint": "^9.39.1"
    "eslint-config-prettier": "^10.1.8"
    "eslint-plugin-prettier": "^5.5.4"
    "eslint-plugin-simple-import-sort": "^12.1.1"
    "prettier": "^3.6.2"
    "typescript": "^5.9.3"
    "typescript-eslint": "^8.45.0"

onlyBuiltDependencies:
    - "@parcel/watcher"
    - "@tailwindcss/oxide"
    - "esbuild"
    - "maplibre-gl"
    - "sharp"
    - "unrs-resolver"
    - "vue-demi"
