includeWorkspaceRoot: true

packages:
    - "apps/*"
    - "packages/*"

onlyBuiltDependencies:
    - "@parcel/watcher"
    - "@tailwindcss/oxide"
    - "esbuild"
    - "maplibre-gl"
    - "sharp"
    - "unrs-resolver"
    - "vue-demi"
